### ISSUE TITLE
--from filters by Issue creation time, not by log record creation time

### ISSUE THREAD

**Issue by IlyaSemenov** [kriskbx/gitlab-time-tracker#11] opened 2017-08-10 09:30 UTC
I created an issue on 2017-07-26 and added two time spent records, one on that date and one today (2017-08-10):

![screen shot 2017-08-10 at 16 17 00](https://user-images.githubusercontent.com/128121/29163784-b7e7cab0-7de7-11e7-917e-1a2c7a0d7455.png)

Now if I want to get a time spent report for August, I don't get anything:

```console
$ gtt report semenov/test -f 2017-08-01
🔍  Selected projects: semenov/test
🔍  Resolving "semenov/test"... ✓
📦  Fetching issues... ✓
📦  Fetching merge requests... ✓
📎  Merging reports... ✓
⚙️️  Processing issues... ✓
Error: No issues or merge requests matched your criteria.
```

If I run `gtt report semenov/test -f 2017-07-01`, I get both reports:

```
TIME RECORDS

┌─────────┬─────────────────────┬───────┬─────┬────────┐
│ user    │ date                │ type  │ iid │ time   │
├─────────┼─────────────────────┼───────┼─────┼────────┤
│ semenov │ 26.07.2017 14:52:49 │ Issue │ 1   │ 2h 30m │
├─────────┼─────────────────────┼───────┼─────┼────────┤
│ semenov │ 10.08.2017 16:06:29 │ Issue │ 1   │ 2h     │
└─────────┴─────────────────────┴───────┴─────┴────────┘
```

I bisected this to `-f 2017-07-26` showing report and `-f 2017-07-27` (the next date after Issue creation) not showing anything.

This is GitLab 9.4.1, gtt 1.5.4.

Is it something imposed by GitLab API, or a bug in gtt? Is there a way to get a report for time log records within a certain range regardless of the corresponding issues' creation date?

**Comment by kriskbx** [comment] 2017-08-10 09:53
`--from` filters by comment creation time, not by issue creation time. I don't think this is a bug: `gtt` filters issues before getting the comments/notes by their `updated_at` timestamp. I had some problems with GitLabs API caching in the past and my guess is that the APIs issue index has not been cleared from the cache after creating the comment. Can you try the same command later this day? If I'm right this will just work fine when GitLabs cache expires.

Nethertheless: this bugs me: maybe we should implement a `--force-update` (naming is wip) option, so that `gtt` will download all comments/notes regardless of the `updated_at` timestamp of the issue to counter GitLabs caching behaviour.

**Comment by IlyaSemenov** [comment] 2017-08-10 11:52
`updated_at` timestamp was indeed set to 2 weeks ago:

![screen shot 2017-08-10 at 18 44 43](https://user-images.githubusercontent.com/128121/29169036-1300e51c-7dfc-11e7-98c6-72c8fb1fd1ea.png)

Could it be GitLab simply not changing `updated_at` when one only adds `/spend XXX`? I posted a text comment and the update time immediately changed to today.

**Comment by kriskbx** [comment] 2017-08-14 11:43
I did some testing and it seems that you are right. I'm not entirely sure but I kinda remember that this worked in the past, so my guess is that it's caused by a recent GitLab update or my memory is simply fooling me... I dunno.

I just pushed version `1.5.5` that includes a fix for this. Make sure to [update accordingly](https://github.com/kriskbx/gitlab-time-tracker#updating). Unfortunately this means an overall speed decrease when creating reports.

**Closed by kriskbx** 2017-08-14 11:43 UTC
